---
- hosts: all
  gather_facts: false
  become: true
  tasks: 
    - include: docker.yml

    - name: Swarm join
      shell: docker swarm join --token $(cat /vagrant/worker_token) {{ manager_ip }}:2377
